### ISSUE TITLE
fix rsync access for mac os sequoia

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/sdss_access#70]
Hi @havok2063 ,

Would you please make a change to the get_task_out method in rsync.py, changing line 32:

`command = "rsync -R %(source)s*" % task`

to

`command = "rsync -Ri %(source)s*" % task`

as discussed on slack https://sdss5.slack.com/archives/C55SWKMT2/p1734396523145819 ?

Thanks,
Joel

**Comment by havok2063** [comment]
For actual transparency, a user reported the following error when using `sdss_access` on Mac OS Sequoia, Python 3.12, or 3.13, using rsync 2.6.9.  

```
from sdss_access import RsyncAccess
access = RsyncAccess(verbose = True)
access.remote()
access.add('allStar', apred=1.3, telescope='apo25m')
access.set_stream()

rsync -R rsync://sdss5@dtn.sdss.org/sdsswork/mwm/apogee/spectro/redux/1.3/summary/allStar-1.3-apo25m.fits*
[ERROR]: Traceback (most recent call last):
  File "/software/pkg/miniconda/3.13/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-f43dbf15e80a>", line 1, in <module>
    access.set_stream()
  File "/software/pkg/miniconda/3.13/lib/python3.12/site-packages/sdss_access/sync/baseaccess.py", line 153, in set_stream
    self.set_stream_task(task)
  File "/software/pkg/miniconda/3.13/lib/python3.12/site-packages/sdss_access/sync/rsync.py", line 60, in set_stream_task
    out = self.get_task_out(task=task)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/pkg/miniconda/3.13/lib/python3.12/site-packages/sdss_access/sync/rsync.py", line 37, in get_task_out
    raise AccessError("Return code %r\n%s" % (status, err))
sdss_access.path.path.AccessError: Return code 1
b'usage: rsync [-0468BCDEFHIKLOPRSTWVabcdghklnopqrtuvxyz] [-e program] [-f filter]\n\t[--8-bit-output] [--address=sourceaddr]\n\t[--append] [--backup-dir=dir] [--bwlimit=limit] [--cache | --no-cache]\n\t[--compare-dest=dir] [--contimeout] [--copy-dest=dir] [--copy-unsafe-links]\n\t[--del | --delete-after | --delete-before | --delete-during]\n\t[--delay-updates] [--dirs] [--no-dirs]\n\t[--exclude] [--exclude-from=file]\n\t[--extended-attributes]\n\t[--existing] [--force] [--ignore-errors]\n\t[--ignore-existing] [--ignore-non-existing] [--include]\n\t[--include-from=file] [--inplace] [--keep-dirlinks] [--link-dest=dir]\n\t[--max-delete=NUM] [--max-size=SIZE] [--min-size=SIZE]\n\t[--modify-window=sec] [--no-motd] [--numeric-ids]\n\t[--out-format=FMT] [--partial] [--password-file=pwfile] [--port=portnumber]\n\t[--progress] [--protocol] [--read-batch=file]\n\t[--remove-source-files] [--rsync-path=program] [--safe-links] [--size-only]\n\t[--sockopts=sockopts] [--specials] [--suffix] [--super] [--timeout=seconds]\n\t[--only-write-batch=file | --write-batch=file]\n\tsource ... directory\n'
```
The error does not occur on Mac OS Sonoma.  One issue could be that Mac unofficially switched to `openrsync` with Sequoia.  

Adding the `-i` option seems to fix the issue, and now outputs the following:
```
receiving file list ... done
.d..tp... mwm/
.d..t.... mwm/apogee/
.d..t.... mwm/apogee/spectro/
.d..t.... mwm/apogee/spectro/redux/
.d..t.... mwm/apogee/spectro/redux/1.3/
.d..t.... mwm/apogee/spectro/redux/1.3/summary/
>f..tp... mwm/apogee/spectro/redux/1.3/summary/allStar-1.3-apo25m.fits
```

**Comment by havok2063** [comment]
The fix is because `-i` is a short-hand also for `--list-only`

`--list-only             list the files instead of copying them`

and the older rsync works without it, but the rsync on sequoia is either expecting a destination (none provided) or the `-i` option since `--list-only` doesn't expect a destination.

**Comment by joelbrownstein** [comment]
I tested the branch on a mac running Sequoia, confirming the bug is fixed:

```
[joel@trinity:~]$ sw_vers; ipython
ProductName:            macOS
ProductVersion:         15.2
BuildVersion:           24C101
Python 3.12.8 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 11:37:13) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sdss_access import RsyncAccess
ac
cIn [2]: access = RsyncAccess(verbose = True)

In [3]: access.remote()
authentication for netloc=data.sdss5.org set for username=sdss5

In [4]: access.add('allStar', apred=1.3, telescope='apo25m')

In [5]: access.set_stream()
rsync -Ri rsync://sdss5@dtn.sdss.org/sdsswork/mwm/apogee/spectro/redux/1.3/summary/allStar-1.3-apo25m.fits*
SDSS_ACCESS> Reducing the number of streams from 5 to 1, the number of download tasks.

In [6]: access.commit()
SDSS_ACCESS> CREATE /var/folders/x4/m14y7w5j45g6cr5tkjqnjwmw0000gn/T/sdss_access/20241217_002
SDSS_ACCESS> streamlets added to /var/folders/x4/m14y7w5j45g6cr5tkjqnjwmw0000gn/T/sdss_access/20241217_002
SDSS_ACCESS> [background]$ 'rsync -avRKL --files-from=/var/folders/x4/m14y7w5j45g6cr5tkjqnjwmw0000gn/T/sdss_access/20241217_002/sdss_access_00.txt rsync://sdss5@dtn.sdss.org/sdsswork /Users/joel/sas/sdsswork/'
SDSS_ACCESS> rsync stream 0 logging to /var/folders/x4/m14y7w5j45g6cr5tkjqnjwmw0000gn/T/sdss_access/20241217_002/sdss_access_00.log
Progress:   0%|                                                                                                       | 0/1 [00:00<?, ?files/s, n_files=1, n_streams=1]
SDSS_ACCESS> Done!
```

**Comment by joelbrownstein** [comment]
I asked Meir Schochet to confirm his issue is also now resolved via [slack](https://sdss5.slack.com/archives/C55SWKMT2/p1734468614289019)
